### ISSUE TITLE
Any chance to make the source of new version public?

### ISSUE THREAD

**Issue by sebastiancarlos** [phphe/cmd-generator#1]
This is the best tool of its kind that I've seen so far, and I would love to contribute some additional classic UNIX tools such as "sed".

**Comment by phphe** [comment]
Thank you. But I am going to public a simpler new version.

**Comment by phphe** [comment]
@sebastiancarlos V3 published.

**Comment by sebastiancarlos** [comment]
Looks impressive, thanks for sharing. I'll take a closer look later. Btw small bug report: I noticed that the `df` command doesn't change to English language.

**Comment by phphe** [comment]
fixed

**Comment by sebastiancarlos** [comment]
Thank you.

Regarding this issue: The reason why I opened it is because this repo only stores data used for generating the UI, but not the entire source code.

I was curious if there's any chance you could make the full codebase public? If given the opportunity, I would be eager to contribute.

**Comment by phphe** [comment]
No. I am not going to make the UI code public.

**Comment by Justman10000** [comment]
> No. I am not going to make the UI code public.

Why? Contributors may want to test how it looks in the end?

**Comment by Justman10000** [comment]
And if you lose the code locally, you could just pull it again from here

**Comment by Justman10000** [comment]
@phphe

**Comment by phphe** [comment]
Thank you, I still have no intention of publicly releasing it.

**Comment by Justman10000** [comment]
> Thank you, I still have no intention of publicly releasing it.

Then it also makes no sense to continue working here
